"""
GenreProfile — central data object passed to all agents.
Created in Phase 1, enriched in Phase 2, used everywhere.
"""

from dataclasses import dataclass, field, asdict
from typing import Optional
import json


@dataclass
class Classification:
    genre_principal: str = ""
    sous_genre: str = ""
    ton: str = ""
    public_cible: str = ""
    style_visuel_attendu: str = ""
    type_gameplay: str = ""   # arcade, casual, hardcore, narrative, puzzle...
    confiance: float = 0.0
    raisonnement: str = ""


@dataclass
class Research:
    mecaniques_populaires: list = field(default_factory=list)
    mecaniques_tendance: list = field(default_factory=list)
    jeux_reference: list = field(default_factory=list)
    pieges_courants: list = field(default_factory=list)
    standards_visuels: list = field(default_factory=list)
    techniques_recommandees: list = field(default_factory=list)
    core_loop_typique: str = ""
    progression_typique: str = ""
    notes_techniques: str = ""


@dataclass
class GenreProfile:
    # Genre identity
    genre_principal: str = ""
    sous_genre: str = ""
    ton: str = ""
    public_cible: str = ""
    type_gameplay: str = ""

    # Mechanics
    mecaniques_obligatoires: list = field(default_factory=list)
    mecaniques_bonus: list = field(default_factory=list)
    mecaniques_a_eviter: list = field(default_factory=list)

    # Visuals & audio
    style_visuel: str = ""
    palette_recommandee: str = ""
    animations_cles: list = field(default_factory=list)
    effets_importants: list = field(default_factory=list)

    # Design
    boucle_core: str = ""
    structure_progression: str = ""
    courbe_difficulte: str = ""

    # Adaptive evaluation criteria (dynamically generated per genre)
    criteres_qc_technique: list = field(default_factory=list)
    criteres_qc_gameplay: list = field(default_factory=list)
    criteres_qc_visuel: list = field(default_factory=list)

    # References
    jeux_reference: list = field(default_factory=list)
    pieges_courants: list = field(default_factory=list)
    notes_techniques: str = ""

    # Rendering technology
    technologie_rendu: str = "canvas2d"  # "canvas2d" ou "threejs"

    # Narrative
    is_narrative: bool = False  # True si le jeu a une histoire/quêtes/dialogues

    # Enriched prompts (final Phase 1 outputs)
    prompt_utilisateur_original: str = ""
    prompt_enrichi: str = ""
    prompt_technique: str = ""

    def to_dict(self) -> dict:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=2)

    @classmethod
    def from_dict(cls, data: dict) -> "GenreProfile":
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})

    def summary(self) -> str:
        """Compact summary for logging."""
        return (
            f"Genre: {self.genre_principal} / {self.sous_genre} | "
            f"Ton: {self.ton} | Public: {self.public_cible} | "
            f"Gameplay: {self.type_gameplay}"
        )


@dataclass
class ModuleArchitecture:
    """Decomposes the game into independent JavaScript modules."""
    modules: list = field(default_factory=list)          # [{"nom", "description", "taille_max", "fonctions_exposees", "variables_requises", "variables_ecrites"}]
    variables_globales: list = field(default_factory=list)   # variables partagées
    variables_init: dict = field(default_factory=dict)        # {nom: expression_init}
    ordre_execution: list = field(default_factory=list)       # ordre des modules
    startup_code: str = "init(); requestAnimationFrame(gameLoop);"
    technologie: str = "canvas2d"                             # "canvas2d" ou "threejs"

    def get_module(self, nom: str) -> dict:
        for m in self.modules:
            if isinstance(m, dict) and m.get("nom") == nom:
                return m
        return {}

    def module_names(self) -> list:
        return [m.get("nom", "") for m in self.modules if isinstance(m, dict)]


@dataclass
class GeneratedModules:
    """Result of the modular generation."""
    modules: dict = field(default_factory=dict)          # {nom: js_code_string}
    architecture: ModuleArchitecture = field(default_factory=ModuleArchitecture)
    modules_valides: list = field(default_factory=list)
    modules_echoues: list = field(default_factory=list)
    modules_regeneres: dict = field(default_factory=dict)  # {nom: nb_tentatives}


@dataclass
class NarrativeContext:
    """Narrative context generated by the narrator agent — optional Phase 2."""
    titre: str = ""
    synopsis: str = ""
    acte1: str = ""
    acte2: str = ""
    acte3: str = ""
    personnages: list = field(default_factory=list)   # [{nom, role, motivation, description}]
    quetes: list = field(default_factory=list)        # [{nom, objectif, recompense, dialogue_intro}]
    dialogues: list = field(default_factory=list)     # [{perso, texte, choix: [{texte, consequence}]}]
    lore: str = ""
    ton_narratif: str = ""

    def to_dict(self) -> dict:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=2)

    @classmethod
    def from_dict(cls, data: dict) -> "NarrativeContext":
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


@dataclass
class ConceptionContext:
    """Aggregates Phase 2 outputs."""
    genre_profile: GenreProfile = field(default_factory=GenreProfile)
    gdd: dict = field(default_factory=dict)           # Game Design Document
    tech_specs: dict = field(default_factory=dict)    # Spécifications techniques
    ux_specs: dict = field(default_factory=dict)      # Guidelines UX/UI
    level_design: dict = field(default_factory=dict)  # Design des niveaux
    narrative_context: Optional[NarrativeContext] = None  # Sortie de agent_scenariste (si is_narrative)

    def to_context_string(self) -> str:
        """Returns a fully formatted context string for the creator agent."""
        parts = [
            "=== GENRE PROFILE ===",
            self.genre_profile.to_json(),
            "\n=== GAME DESIGN DOCUMENT ===",
            json.dumps(self.gdd, ensure_ascii=False, indent=2),
            "\n=== TECHNICAL SPECIFICATIONS ===",
            json.dumps(self.tech_specs, ensure_ascii=False, indent=2),
            "\n=== UX/UI GUIDELINES ===",
            json.dumps(self.ux_specs, ensure_ascii=False, indent=2),
            "\n=== LEVEL DESIGN ===",
            json.dumps(self.level_design, ensure_ascii=False, indent=2),
        ]
        if self.narrative_context:
            parts.append("\n=== NARRATIVE CONTEXT ===")
            parts.append(self.narrative_context.to_json())
        return "\n".join(parts)


@dataclass
class EvaluationResult:
    """Result from a single evaluation agent."""
    agent_name: str = ""
    score: float = 0.0          # 0-10
    criteres: list = field(default_factory=list)   # [{nom, score, poids, commentaire}]
    issues: list = field(default_factory=list)     # [{severite, description, suggestion}]
    points_forts: list = field(default_factory=list)
    commentaire_global: str = ""


@dataclass
class EvaluationBundle:
    """Aggregates all Phase 4 evaluation results."""
    qc_technique: EvaluationResult = field(default_factory=EvaluationResult)
    qc_gameplay: EvaluationResult = field(default_factory=EvaluationResult)
    qc_visuel: EvaluationResult = field(default_factory=EvaluationResult)
    execution: EvaluationResult = field(default_factory=EvaluationResult)
    playtester: EvaluationResult = field(default_factory=EvaluationResult)
    anti_pattern: EvaluationResult = field(default_factory=EvaluationResult)
    benchmark: EvaluationResult = field(default_factory=EvaluationResult)

    def score_global(self) -> float:
        """Global weighted score — calibrated for high-quality game demos.

        Weights:
        - Gameplay (depth + systems):  25% — most impactful in a demo
        - Technical (correct code):     20% — fundamental but not the dominant factor
        - Visual (quality):             15% — the demo must look good
        - Execution (browser test):     20% — validates it runs (headless Playwright)
        - Playtester (fun factor):      15% — does the player want to come back?
        - Anti-pattern:                  3% — merged into gameplay, reduced weight
        - Benchmark (genre comparison):  2% — contextual only
        """
        weights = {
            "qc_technique": 0.20,
            "qc_gameplay":  0.25,
            "qc_visuel":    0.15,
            "execution":    0.20,
            "playtester":   0.15,
            "anti_pattern": 0.03,
            "benchmark":    0.02,
        }
        # If the playtester is a fallback (quota exhausted), exclude it from the score
        # and redistribute its weight proportionally to avoid unfair penalization.
        playtester_fallback = (
            self.playtester.score == 5.0
            and "non disponible" in self.playtester.commentaire_global.lower()
        )
        if playtester_fallback:
            excluded_weight = weights.pop("playtester")
            # Redistribute weight proportionally across remaining agents
            total_remaining = sum(weights.values())
            weights = {k: v + v / total_remaining * excluded_weight for k, v in weights.items()}

        total = 0.0
        for attr, w in weights.items():
            result = getattr(self, attr)
            total += result.score * w
        return round(total, 2)

    def has_blocking_issues(self) -> bool:
        """
        Returns True if the game is likely unplayable.
        C1 — Blocking criteria:
        - Execution score < 5.0 (headless test failed — game likely broken)
        - Technical score < 5.5 (code too defective)
        - Execution score < 6.5 AND a critical issue in QC Technical
        """
        # C1: minimum thresholds per dimension
        if self.execution.score < 5.0:
            return True
        if self.qc_technique.score < 5.5:
            return True

        # Borderline execution (5.0–6.5): block if QC Technical reports a critical bug
        if self.execution.score < 6.5:
            for issue in self.qc_technique.issues:
                if issue.get("severite") == "critique":
                    return True

        return False

    def playability_score(self) -> float:
        """
        C3: Dedicated playability score — separates "pretty" from "playable".
        Based only on execution + technical + gameplay.
        Minimum required to save: 6.0.
        """
        weights = {
            "execution":    0.40,
            "qc_technique": 0.30,
            "qc_gameplay":  0.30,
        }
        total = 0.0
        for attr, w in weights.items():
            result = getattr(self, attr)
            total += result.score * w
        return round(total, 2)

    def all_issues(self) -> list:
        """All issues from all agents, sorted by severity."""
        issues = []
        severity_order = {"critique": 0, "majeur": 1, "mineur": 2}
        for attr in ["qc_technique", "qc_gameplay", "qc_visuel", "execution",
                     "playtester", "anti_pattern", "benchmark"]:
            result = getattr(self, attr)
            for issue in result.issues:
                issues.append({**issue, "source": attr})
        issues.sort(key=lambda x: severity_order.get(x.get("severite", "mineur"), 2))
        return issues

    def summary(self) -> str:
        scores = {
            "Technique": self.qc_technique.score,
            "Gameplay": self.qc_gameplay.score,
            "Visuel": self.qc_visuel.score,
            "Execution": self.execution.score,
            "Playtester": self.playtester.score,
            "Anti-pattern": self.anti_pattern.score,
            "Benchmark": self.benchmark.score,
        }
        lines = [f"  {k}: {v}/10" for k, v in scores.items()]
        lines.append(f"  GLOBAL: {self.score_global()}/10")
        return "\n".join(lines)
